### ISSUE TITLE
Domain on 'error' event listener

### ISSUE THREAD

**Issue by dhuertas** [imrefazekas/connect-rest#23]
Hi,
When using connect-rest along with express and node.js domain functionality, as in:
```
var rest = require('connect-rest');
var express = require('express');

var options = {
  context: "/api",
  domain: require('domain').create(),
};

var app = express();
app.use(rest.rester(options));
```
Returned function restMaker adds an 'error' event listener for every request received (file lib/connect-rest.js, line 385), thus causing the following warning message:
```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
```
It does not happen when domain functionality is not used though.

**Comment by ciscoheat** [comment]
I can confirm the same problem, using v0.10.33.

**Comment by imrefazekas** [comment]
Guys, good catch, thank you very much!

Yep, domain handling was incorrect. I followed the reference of NodeJS on this matter and rewrite those lines according to this page:
http://nodejs.org/api/domain.html#domain_domain

and updated the document where you can see how you can refine the default behaviour of the lib.

I hope it resolve your issues. If you have any inconvenience, please do not hesitate to write me, I will be happy to develop to please your development needs. :)

Thanks again!

**Comment by ciscoheat** [comment]
Thanks for your quick response and fix, it seems to work very well! :)

**Comment by ciscoheat** [comment]
Much better than my crude fix, hehe.

**Comment by ciscoheat** [comment]
Oh, would it be possible to pass the error to the callbacks, so the signatures would be `err, req, res`?

**Comment by imrefazekas** [comment]
Sure. Here you go:
connect-rest@1.6.6

**Comment by ciscoheat** [comment]
Wow, talk about realtime updating! Thanks again. :)

**Comment by dhuertas** [comment]
Checked with 1.6.6 and works great. Good job ;)

Thank you!
