### ISSUE TITLE
protectors should allow returning 400/401/403 responses.

### ISSUE THREAD

**Issue by rohitkhode** [imrefazekas/connect-rest#24]
It appears that a false return from protector causes a 404 which is not very useful in many cases.
in case protector denies access to a resource:
1. is should be possible to return other status codes e.g. 400/401/403.
2. also a custom response body containing a useful message would be good.

**Comment by imrefazekas** [comment]
Hello,

By default, you cannot. The idea behind the protector is to decide if a given service should respond to a call or not.
Basically the concept to able to define service functions which respond to requests. The 1:n quantity relationship is allowed and encouraged. So multiple service functions might react to a single request.
Therefore, the API_KEY, protector features are working like filters to filter out the defined service functions which should not participate in the process. So by default protector is just a filter.

But I started to realize, that that filter-based functionality lost its touch and should be reconsidered to give more space for customisation.

Please give me a little time and after made some refinements, your desired feature will be at your disposal. Actually, even more. ;)

**Comment by rohitkhode** [comment]
thanks,

Since adding other middleware functions before 'action' isn't possible (or so I believe), I am trying to use protector as authorization middleware. 
I feel the name 'protector' is quite intuitive for this purpose. But I soon realized the limitations when 'Not Authorized/Forbidden' responses were returned as 404.

```javascript
    var authUtils = require('../authUtils');
    var restURL = '/resource';

    rest.get(restURL, controller.list);
    rest.post({path:restURL, protector : authUtils.isAuthenticated }, controller.create);

    rest.get(restURL+'/:id', controller.read);
    rest.post({path:restURL+'/:id', protector : authUtils.isOwner }, controller.update);
    rest.del({path:restURL+'/:id', protector : authUtils.isAdmin}, controller.delete);
```

**Comment by imrefazekas** [comment]
Hello,

Sorry for the big delay, I released a new version which allows you to respond requests by a protector. I hope it fits your needs. :)

**Comment by rohitkhode** [comment]
Thanks a ton!
