### ISSUE TITLE
Missing: HTTP OPTIONS method

### ISSUE THREAD

**Issue by exiquio** [imrefazekas/connect-rest#30]
I'm trying to do [Preflighted CORS Requests] (https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests) and I don't have access to HTTP OPTIONS while using connect-rest:

```
TypeError: Cannot call method 'find' of undefined.
  at getRouterMatching (...lib/connect-rest.js:384:15)
```

In order to make Preflighted CORS requests, I believe I'd need connect-rest to implement the OPTIONS method. Is there an obvious reason this method wasn't implemented? If not, is there anything stopping it from being implemented?

I can make that change myself and I could send out a Pull Request, but I want to understand the situation fully. Node.js and connect-rest are relatively new to me. 

Thanks

**Comment by exiquio** [comment]
I'm think I'm misunderstanding what I should be doing with connect-cors while using connect-rest. I'm closing this for now. I will create another issue if there's still and issue, but only if I'm 100% on what the problem is. My apologies.

**Comment by exiquio** [comment]
Ok. I definitely need the OPTIONS method. I did test without modifications (I just followed the existing pattern with HTTP methods in lib/connect-rest.js) to connect-rest and I end up back at the same error. With the modifications, I'm golden. So, my questions stand and I want to add one more: How do I run the tests? I'd like to submit a pull request pending the answers to these questions. Thanks.

**Comment by imrefazekas** [comment]
Hello!

Options method is not supported from v1.8.0. I hope this helps. If some features you still miss, do not hesitate to open a ticket. :)

**Comment by imrefazekas** [comment]
To check headers for cors, the cors package for Connect/Express can be used:
https://www.npmjs.com/package/cors

Cors in general is on my list to improve connect-rest, but not yet cleared the picture how to do it in an elegant way. That cors solution is not too handy when you REST API is complex and structured. :(

**Comment by exiquio** [comment]
Thanks!
