### ISSUE TITLE
About the support for the "cors" Node module

### ISSUE THREAD

**Issue by TX-DSS** [imrefazekas/connect-rest#31]
I want to know whether "connect-rest" support "cors" like this: 

var cors = require('cors');
var corsOptions = {
  origin: 'http://...'
};
rest.post('/books/add', cors(corsOptions), functionN0 );

When I try above, got this Error:
TypeError: Object #<Object> has no method 'setHeader'
    at applyHeaders (/Users/DSS/Dev/GitDoc/pow/node_modules/cors/lib/index.js:146:15)

**Comment by imrefazekas** [comment]
Hello,

That style (Connect) is working:

    app.use(cors());

Your code follows the syntax of Express when you can enumerate 2 handlers to the same path. Connect-rest is Connect-based, so "supports" the cors as middleware.

**Comment by TX-DSS** [comment]
Thanks for explanation
